version: "3.3"
services:
  spark-master:
    build: .
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
      - 8088:18080
    networks:
      - spark-network
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
      - "SPARK_PUBLIC_DNS=localhost"
      - "SPARK_CONF_DIR=/conf"
    volumes:
      - ./data:/opt/spark-data
      - ./conf:/opt/spark-conf
      - ./logs:/opt/spark-logs
    command: "/start-master.sh"
  spark-worker:
    build: .
    depends_on:
      - spark-master
    ports:
      - "8081-8091:8080"
    networks:
      - spark-network
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8080"
      - "SPARK-LOCAL_IP=spark-worker"
      - "SPARK_PUBLIC_DNS=localhost"
      - "SPARK_WORKER_CORES=2"
      - "SPARK_WORKER_MEMORY=1g"
      - "SPARK_CONF_DIR=/conf"
    volumes:
      - ./data:/opt/spark-data
      - ./conf:/opt/spark-conf
      - ./logs:/opt/spark-logs
    command: "/start-worker.sh"
networks:
  spark-network:
    driver: bridge
    ipam:
      driver: default
